#!/bin/bash

sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh
xfce4-power-manager &

bspc config top_padding 27

bspc config window_gap 0
bspc config left_padding 0
bspc right_padding 0
bspc config bottom_padding 0

bspc monitor -d I II III IV V

bspc rule -a Emacs state=tiled

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/bspwm/bspwm_updater.sh
