#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh
nitrogen --set-auto ~/Wallpaper.png & 
picom --experimental-backend &
xfce4-power-manager &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V

bspc config -n $(bspc query -N -n) border_width 0

bspc config active_border_color "#426370"
bspc config border_width         5
bspc config window_gap          10

bspc rule -a Emacs state=tiled

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/bspwm/bspwm_updater.sh
